services:
    # class: BZM\CoreBundle\Form\ProjectType
    # arguments: ['@service_container']
    # tags:
    #     - { name: installform.type }
#    core.example:
#        class: BZMCoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
